from .compatibility import (
    is_aggregation_supported,
    is_dimension_eligible,
    supported_aggregations,
)
from .contracts import (
    AggregationFunction,
    AnalyticsDimensionDescriptor,
    AnalyticsMeasureDescriptor,
    AnalyticsQuery,
    AnalyticsQueryError,
    AnalyticsResult,
    AnalyticsResultColumn,
    AnalyticsResultRole,
    DatasetColumnDescriptor,
    DatasetDetails,
    DatasetListResult,
    DatasetPreviewResult,
    DatasetReference,
    DatasetStatistics,
    DatasetSummary,
    Dimension,
    FilterClause,
    FilterOperator,
    InvalidAnalyticsIdentifierError,
    InvalidAnalyticsQueryError,
    InvalidFilterError,
    InvalidMeasureError,
    InvalidSortError,
    Measure,
    SortClause,
    SortDirection,
)
from .discovery import DatasetDiscoveryRepository, DatasetDiscoveryService
from .exceptions import (
    AnalyticsQueryError as AnalyticsDomainQueryError,
)
from .exceptions import (
    InvalidAggregationError,
    InvalidExecutionPlanError,
    InvalidIdentifierError,
)
from .planner import (
    AnalyticsExecutionPlan,
    AnalyticsQueryPlanner,
    ResolvedDimension,
    ResolvedFilter,
    ResolvedMeasure,
    ResolvedSort,
)
from .repository import AnalyticsRepository

__all__ = [
    "AggregationFunction",
    "AnalyticsQuery",
    "AnalyticsQueryError",
    "AnalyticsResult",
    "AnalyticsResultColumn",
    "AnalyticsResultRole",
    "DatasetReference",
    "Dimension",
    "FilterClause",
    "FilterOperator",
    "InvalidAnalyticsIdentifierError",
    "InvalidAnalyticsQueryError",
    "InvalidFilterError",
    "InvalidMeasureError",
    "InvalidSortError",
    "Measure",
    "SortClause",
    "SortDirection",
    "DatasetSummary",
    "DatasetListResult",
    "DatasetColumnDescriptor",
    "AnalyticsDimensionDescriptor",
    "AnalyticsMeasureDescriptor",
    "DatasetDetails",
    "DatasetPreviewResult",
    "DatasetStatistics",
    "AnalyticsDomainQueryError",
    "InvalidAggregationError",
    "InvalidExecutionPlanError",
    "InvalidIdentifierError",
    "InvalidSortError",
    "DatasetNotAnalyticsReadyError",
    "AnalyticsQueryPlanner",
    "AnalyticsExecutionPlan",
    "ResolvedDimension",
    "ResolvedFilter",
    "ResolvedMeasure",
    "ResolvedSort",
    "AnalyticsRepository",
    "DatasetDiscoveryRepository",
    "DatasetDiscoveryService",
    "is_aggregation_supported",
    "is_dimension_eligible",
    "supported_aggregations",
]
