"""create core statflow domain tables

Revision ID: 6f3e7ff115e1
Revises: a5e56a056bd8
Create Date: 2026-07-14 06:43:40.034329

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6f3e7ff115e1'
down_revision: Union[str, Sequence[str], None] = 'a5e56a056bd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_code'), 'categories', ['code'], unique=True)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_table('datasets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_name', sa.String(length=150), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('reference_year', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provinces',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provinces_code'), 'provinces', ['code'], unique=True)
    op.create_index(op.f('ix_provinces_name'), 'provinces', ['name'], unique=True)
    op.create_table('districts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('province_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['province_id'], ['provinces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('province_id', 'code', name='uq_districts_province_code')
    )
    op.create_index(op.f('ix_districts_province_id'), 'districts', ['province_id'], unique=False)
    op.create_table('indicators',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('source_name', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indicators_category_id'), 'indicators', ['category_id'], unique=False)
    op.create_index(op.f('ix_indicators_code'), 'indicators', ['code'], unique=True)
    op.create_table('data_points',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('indicator_id', sa.UUID(), nullable=False),
    sa.Column('province_id', sa.UUID(), nullable=True),
    sa.Column('district_id', sa.UUID(), nullable=True),
    sa.Column('value', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('reference_year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(province_id IS NOT NULL AND district_id IS NULL) OR (district_id IS NOT NULL AND province_id IS NULL)', name='ck_data_points_exactly_one_geo'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicators.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['province_id'], ['provinces.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_points_dataset_id'), 'data_points', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_data_points_district_id'), 'data_points', ['district_id'], unique=False)
    op.create_index(op.f('ix_data_points_indicator_id'), 'data_points', ['indicator_id'], unique=False)
    op.create_index(op.f('ix_data_points_province_id'), 'data_points', ['province_id'], unique=False)
    op.create_index('uix_data_points_district_level', 'data_points', ['dataset_id', 'indicator_id', 'district_id', 'reference_year'], unique=True, postgresql_where=sa.text('district_id IS NOT NULL AND province_id IS NULL'))
    op.create_index('uix_data_points_province_level', 'data_points', ['dataset_id', 'indicator_id', 'province_id', 'reference_year'], unique=True, postgresql_where=sa.text('province_id IS NOT NULL AND district_id IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uix_data_points_province_level', table_name='data_points', postgresql_where=sa.text('province_id IS NOT NULL AND district_id IS NULL'))
    op.drop_index('uix_data_points_district_level', table_name='data_points', postgresql_where=sa.text('district_id IS NOT NULL AND province_id IS NULL'))
    op.drop_index(op.f('ix_data_points_province_id'), table_name='data_points')
    op.drop_index(op.f('ix_data_points_indicator_id'), table_name='data_points')
    op.drop_index(op.f('ix_data_points_district_id'), table_name='data_points')
    op.drop_index(op.f('ix_data_points_dataset_id'), table_name='data_points')
    op.drop_table('data_points')
    op.drop_index(op.f('ix_indicators_code'), table_name='indicators')
    op.drop_index(op.f('ix_indicators_category_id'), table_name='indicators')
    op.drop_table('indicators')
    op.drop_index(op.f('ix_districts_province_id'), table_name='districts')
    op.drop_table('districts')
    op.drop_index(op.f('ix_provinces_name'), table_name='provinces')
    op.drop_index(op.f('ix_provinces_code'), table_name='provinces')
    op.drop_table('provinces')
    op.drop_table('datasets')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_code'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
